### PR TITLE
Temporarily hide the TypeOfService selector and allow empty values to…

### PR DESCRIPTION
**Pull request by johanib**
… prevent unsubmittable forms

Resolves https://github.com/SURFnet/sp-dashboard/issues/1321

### CODE REVIEW

**Comment by johanib** [comment]
@MKodde As discussed, I tested the other form as wel. There were no errors.

**Review by MKodde — APPROVED** [review]
If 'soft' disabling is OK with the PM, this is fine with me. Maybe refer to the ticket where this is going to be fixed in the PR description? Is saw a reference in the TODO comment, might be handy to link it here too?

**Comment by johanib** [comment]
Will be re-enabled in https://github.com/SURFnet/sp-dashboard/issues/1322

**Review by MKodde — COMMENTED** [review]
We reviewed this IRL; this temporary solution will be rolled back and tweaked in the near future

**Pull request merged**
