### PR TITLE
Add additional secyurity headers to response

### PR DESCRIPTION
**Pull request by pablothedude**
It was suggested to add more security headers to the responses by Cure53.
Those are now added.

https://www.pivotaltracker.com/story/show/167065629

### CODE REVIEW

**Comment by pablothedude** [comment]
A good suggestion, I will look into this.

**Comment by pablothedude** [comment]
Added the bundle and used the config from profile, the only thing which was changed was the use of the `Content-Security-Policy` configuration (see extra parameters in `forced_ssl` configuration section).

**Comment by MKodde** [comment]
Thanks for adding the security bundle. One thing caught my eye, and that's the addition of the `spdashboard_saml_remote_idp_host` parameter. This change seems unrelated to this PR?

**Comment by pablothedude** [comment]
The `spdashboard_saml_remote_idp_host` parameter is needed to support external redirects form EB. Else I was unable to log in, the same was done with Profile I think for the same reason.

**Pull request merged**
