### PR TITLE
 Show OIDC confirmation screen after publishing

### PR DESCRIPTION
**Pull request by MKodde**
The modal window is displayed after a successful publication to manage.
This is done only once. After the action was performed, the in memory
(session) clone is removed from the session.

The modal window itself is functioning like the type selection modal.

More details: https://www.pivotaltracker.com/story/show/162119902

:warning: This PR is built on top of an unfinished PR #189 Either rebase or await merging this PR until that feature is merged back to develop.

### CODE REVIEW

**Comment by MKodde** [comment]
During your functional test, was commit 'Show OIDC confirmation screen after publishing' on revision 8ca0f9c3? I fixed this issue when I was testing this myself. To check this, the `oidcConfirmationModalAction` was previously set wit the `* @Route("/entity/published/test", name="entity_published_test")` annotation.
`

**Comment by MKodde** [comment]
Hi, just tested it again after rebasing onto your #189 branch. It seems to work just fine. Can you retry?

screenshot from 2018-12-13 09-35-47

**Comment by pablothedude** [comment]
Sweet!

**Comment by pablothedude** [comment]
I've cherrypicked the  changes in a seperate PR after the changes in the oidc branch. This
was done to tackle the extensive conflicts in this PR. #204 

Therefore I will close this one.

**Pull request closed without merging**
